version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./stock-service:/var/www/html
    links:
      - phpfpm
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=eldho123
    restart: always

  phpfpm:
    image: phpfpm
    container_name: phpfpm
    ports:
      - '9000:9000'
    volumes:
      - ./stock-service:/var/www/html
    links:
      - mysql
    restart: always
